@extends('frontend.layout')

@section('content')
<section class="section-page-content" style="padding-top: 30px">
    <div class="container">
        <div class="row">
            <div id="primary" class="col-sm-12 col-md-12">
<h1>Mticket Terms & Condition</h1><br>
<p>Halo, selamat datang di situs&nbsp;<a href="http://www.mticket.asia/" rel="noopener noreferrer" target="_blank">www.mticket.asia</a>&nbsp;yang dikelola dan dimiliki oleh PT EDRUS EXPO ANUGERAH, selaku pemilik brand MTICKET (&ldquo;Situs&rdquo;). PT EDRUS EXPO ANUGERAH adalah perseroan terbatas yang bergerak di bidang teknologi yaitu penyediaan piranti lunak (software) berupa platform untuk memudahkan dan membuat pengalaman penggunaan terbaik dalam menikmati event bagi kamu dan event creator (untuk selanjutnya disebut &ldquo;MTICKET&rdquo; atau &ldquo;Kami&rdquo;). Setiap orang atau badan hukum yang menggunakan, mengakses, memanfaatkan dan/atau membuat akun di Situs Kami (untuk selanjutnya disebut &ldquo;Kamu&rdquo;) dengan ini dianggap telah memahami, membaca, menerima dan setuju akan ketentuan penggunaan Situs dan layanan MTICKET, sebagaimana akan diuraikan di bawah ini (untuk selanjutnya disebut &ldquo;Ketentuan Penggunaan&rdquo;).</p>

<p>Ketentuan Penggunaan ini adalah perjanjian yang sah dan mengikat antara Kamu dan MTICKET. Silahkan untuk membatalkan akun Kamu dan/atau keluar dari Situs serta tidak menggunakan, mengakses dan/atau memanfaatkan Situs ini jika Kamu tidak setuju atau tidak ingin terikat dengan Ketentuan Penggunaan ini.</p>

<p>MOHON MEMERIKSA KETENTUAN PENGGUNAAN DAN KEBIJAKAN PRIVASI MTICKET DENGAN SEKSAMA SEBELUM MENGGUNAKAN SITUS DAN LAYANAN MTICKET UNTUK PERTAMA KALI. DENGAN MENDAFTAR, MEMBUAT AKUN DAN/ATAU MENGGUNAKAN SITUS ATAU LAYANAN MTICKET, KAMU SECARA PRIBADI DAN/ATAU BADAN HUKUM YANG KAMU WAKILI TELAH MEMAHAMI DAN SETUJU UNTUK TUNDUK SERTA TERIKAT PADA SELURUH SYARAT DAN KETENTUAN PENGGUNAAN INI DAN KEBIJAKAN PRIVASI MTICKET. DENGAN INI KAMU MENYATAKAN SERTA MENJAMIN KEPADA MTICKET BAHWA KAMU ADALAH PERORANGAN ATAU PERWAKILAN BADAN HUKUM YANG SAH DAN BERHAK UNTUK BERTINDAK SERTA MENGIKATKAN DIRI DALAM PERJANJIAN INI.</p>

<h3>A. Definisi &amp; Interpretasi</h3>

<p>1. Kecuali konteksnya menentukan lain, ungkapan berikut akan memiliki arti sebagai berikut dalam Ketentuan Penggunaan ini:</p>

<p>&quot;MTICKET&quot;, &quot;kita&rdquo;, atau &quot;kami&quot; merujuk kepada PT EDRUS EXPO ANUGERAH, sebuah perseroan terbatas yang didirikan berdasarkan hukum Indonesia dan beralamat di Green Lake City Ruko Crown Blok D No. 17, Petir, Kec. Cipondoh, Kota Tangerang, Banten 15147</p>

<p>&ldquo;Kamu&rdquo; atau &ldquo;Pengguna&rdquo; merujuk pada setiap orang atau badan hukum yang menggunakan, mengakses, memanfaatkan dan/atau membuat akun di&nbsp;<a href="http://www.mticket.com/" rel="noopener noreferrer" target="_blank">www.mticket.com</a>&nbsp;termasuk namun tidak terbatas pada Event Creator dan Pembeli.</p>

<p>&ldquo;Situs&rdquo; berarti&nbsp;<a href="http://www.mticket.com/" rel="noopener noreferrer" target="_blank">www.mticket.com</a>&nbsp;yang dikelola dan dimiliki oleh MTICKET.</p>

<p>&ldquo;Platform&rdquo; berarti Situs kami, versi mobile dari Situs kami, saluran suara dan data, teknologi, piranti lunak, sistem dan media lain yang dimiliki dan dikelola oleh MTICKET dari waktu ke waktu.</p>

<p>&ldquo;Event&rdquo; berarti suatu kegiatan yang bersifat komersial maupun tidak komersial yang diselenggarakan oleh Event Creator yang menggunakan jasa layanan Platform kami untuk menunjang kegiatan acara tersebut.</p>

<p>&ldquo;Event Creator&rdquo; berarti setiap individu, perkumpulan, badan hukum, dan/atau berbagai badan hukum lainnya yang menyelenggarakan Event sebagai penyelenggara, promotor, panitia dan/atau pemilik yang bekerjasama dengan kami menggunakan layanan Platform kami termasuk namun tidak terbatas pada layanan yang kami sediakan di Situs.</p>

<p>&ldquo;Tiket&rdquo; berarti tanda bukti hak yang sah untuk memasuki tempat berlangsungnya Event, menikmati suatu pertunjukan yang dipertunjukan oleh Event, menggunakan dan/atau memanfaatkan suatu kegiatan yang berhubungan dengan Event yang diselenggarakan Event Creator sesuai dengan tanggal, waktu, tempat, jenis dan/atau ketentuan lainnya yang melekat pada tiket masuk tersebut yang telah dipilih, dipesan dan dibeli secara sah oleh Pembeli, baik berbentuk fisik, elektronik atau bentuk media lainnya yang digunakan oleh kami dari waktu ke waktu dan telah dilengkapi dengan kode unik (barcode) sebagai sistem pengamanan pada tiket tersebut.</p>

<p>&ldquo;Mitra&rdquo; berarti pihak yang telah mengadakan kerja sama dengan kami antara lain termasuk namun tidak terbatas pada kerja sama penggunaan kembali platform kami untuk menyediakan Tiket baik secara daring maupun secara langsung tatap muka atau offline.</p>

<p>&ldquo;Pembeli&rdquo; berarti setiap individua dan/atau badan hukum yang membeli dengan harga tertentu atau secara cuma-cuma Tiket yang diselenggarakan oleh Event Creator secara sah dan sesuai dengan Ketentuan Penggunaan ini, syarat dan ketentuan yang berlaku pada tempat Event, syarat dan ketentuan yang ditetapkan oleh Event Creator, serta peraturan perundang-undangan yang berlaku.</p>

<p>&ldquo;Mticket.asia berarti adalah layanan yang kami sediakan untuk kamu Event Creator berupa penyediaan platform untuk menunjang Event yang memberikan kemudahan dengan penggunaan teknologi untuk Event Creator guna membuat, memasarkan, menjual, dan/atau mendistribusikan Event secara mandiri, dimana layanan tersebut dapat berubah dari waktu ke waktu berdasarkan kebijakan kami sendiri.</p>

<p>&ldquo;Biaya Jasa&rdquo; berarti biaya jasa sebagai imbalan kepada kami atas jasa atau produk layanan kami, termasuk namun tidak terbatas pada penyediaan Platform guna menunjang Event kamu, baik berupa uang, presentase maupun jasa yang dapat dinilai, yang kami tetapkan dari waktu ke waktu berdasarkan kebijakan kami sendiri.</p>

<h3>B. Ketentuan Umum</h3>

<p>Jika terjadi konflik atau inkonsistensi antara dua atau lebih ketentuan dalam Ketentuan Penggunaan ini baik dengan ketentuan penggunaan kami lainnya dan/atau ketentuan penggunaan Mitra kami, apakah ketentuan tersebut tercantum dalam dokumen yang sama atau berbeda, konflik atau inkonsistensi tersebut maka MTICKET akan menentukan ketentuan yang berlaku.</p>

<p>Selain Ketentuan Penggunaan ini dan tergantung pada layanan yang dipilih oleh Kamu, Kamu wajib untuk membaca dan menerima aturan dan ketentuan layanan tersebut yang mungkin akan berlaku untuk layanan tersebut.</p>

<p>Perjanjian ini berlaku selama Kamu, Event Creator menggunakan jasa Kami, baik pada saat penyelenggaraan Event maupun pada saat berakhirnya Event sampai dengan Kamu telah memenuhi seluruh kewajiban Kamu berdasarkan perjanjian ini.</p>

<p>MTICKET akan mempublikasikan setiap perubahan yang bersifat substansial atau amandemen dari Ketentuan Penggunaan ini (apabila ada) melalui Platform. Event Creator diwajibkan untuk membaca dengan baik setiap perubahan atau amandemen tersebut sehingga apabila Event Creator tetap menggunakan, mengakses atau memanfaatkan Platform, Event Creator dianggap telah mengetahui, memahami dan menyetujui perubahan atau amandemen tersebut.</p>

<p>Semua pemesanan Tiket oleh Pembeli untuk Event yang diselenggarakan oleh Event Creator melalui Platform kami, merupakan perikatan terpisah dengan perikatan yang timbul dari perjanjian ini berdasarkan Ketentuan Penggunaan ini, yaitu perikatan yang timbul antara Pembeli dengan Event Creator, yang masing-masing pihak terikat dan tunduk pada perikatan tersebut. Untuk menghindari keragu-raguan, Kami merupakan penyedia Platform yang bekerja sama dengan Event Creator, sedangkan keseluruhan Tiket yang dijual kepada Pembeli adalah milik Event Creator. Segala bentuk data dan informasi mengenai Tiket yang Event Creator sediakan kepada Kami, dan Kami informasikan kepada calon Pembeli, merupakan penawaran dari Event Creator kepada calon Pembeli tersebut dimana mengikat untuk Event Creator dan Pembeli dalam hal terjadi pembelian Tiket tersebut. Oleh sebab itu, Kami bukan termasuk dalam pihak dalam hal terjadi sengketa, penuntutan hak, gugatan hak, permintaan hak, penggantian rugi, kerugian yang timbul, cidera yang timbul, kematian yang timbul dan/atau klaim hak atas hak apapun yang timbul terkait secara langsung maupun tidak langsung dari penyelenggaran Event yang diminta oleh Event Creator kepada Pembeli dan begitupun sebaliknya dari Pembeli kepada Event Creator, termasuk oleh pihak ketiga manapun yang merasa dirugikan oleh penyelenggaraan Event oleh Event Creator.</p>

<p>Untuk menghindari keragu-raguan, Event Creator telah memahami dan menyetujui bahwa MTICKET tidak memberikan jaminan dalam bentuk apapun atas keberhasilan penyelenggaran Event baik dalam bentuk hasil penjualan Tiket maupun kelancaran pelaksanaan Event. Event Creator dengan ini membebaskan dan melepaskan MTICKET dan menanggung dari segala bentuk tuntutan, gugatan, permintaan, kerugian, klaim, dan/atau segala bentuk penggantian hak oleh pihak manapun termasuk Event Creator sendiri yang timbul akibat dari termasuk namun tidak terbatas pada hasil penjualan Tiket dan penyelenggaran Event.</p>

<h3>C. Akun Event Creator</h3>

<p>Setiap Event Creator yang hendak menggunakan dan memanfaatkan layanan kami, termasuk layanan mticket.com, untuk menunjang Event kamu, wajib membuat akun pada sistem MTICKET.</p>

<p>Syarat untuk membuat akun adalah pengisiian data dan informasi oleh Event Creator yang kebenaran, validitas, legalitas, dan keabsahaannya dijamin oleh Kamu.</p>

<p>Setiap perbuatan dan tindakan dengan menggunakan akun tersebut merupakan tanggung jawab penuh Event Creator sebagai pembuat dan pemilik akun tersebut, termasuk segala bentuk penyalahgunaan yang dilakukan oleh pihak lain dan/atau Event Creator sendiri. Oleh sebab itu, Event Creator diwajibkan untuk menjaga kerahasiaan data dan informasi yang berkaitan dengan akun tersebut. Event Creator membebaskan dan melepaskan MTICKET dari tanggung jawab dalam bentuk apapun terkait dengan penggunaan akun tersebut.</p>

<p>Dalam pembuatan akun tersebut, segala data dan informasi yang diisi oleh Event Creator adalah dalam penguasaan dan kepemilikan penuh dari Event Creator, di mana Event Creator bertanggungjawab penuh atas kebenaran setiap data dan informasi yang diisi oleh Event Creator, dan segala bentuk kelalaian, kesalahan, kealpaan, typo, dan/atau kesalahan dalam bentuk dan alasan apapun yang menyebabkan data dan informasi tersebut menjadi tidak bermakna sebagaimana yang akan dimaksud oleh Event Creator menjadi tanggung jawab penuh Event Creator, baik yang menimbulkan kerugian maupun yang tidak, termasuk namun tidak terbatas pada kesalahan nomor rekening, jadwal acara, tempat acara akan menjadi tanggung jawab Event Creator. Event Creator diwajibkan untuk mengisi segala informasi dan data dalam pembuatan akun secara akurat, seksama, hati-hati dan penuh ketelitian.</p>

<p>Kamu sebagai Event Creator dengan ini menyatakan dan menjamin kepada Kami bahwa kamu adalah badan hukum yang berhak, perwakilan sah yang berwenang, pemilik hak, dan/atau telah mendapat seluruh persetujuan yang diperlukan dalam membuat akun serta mengisi segala data dan informasi dalam pembuatan akun Kamu.</p>

<p>Kamu sebagai Event Creator dengan ini menyatakan dan menjamin kepada Kami bahwa segala data dan informasi yang diberikan dan diisi dalam pembuatan akun Kamu merupakan data dan informasi yang legal, valid, sah, dan menjadi kewenangan Kamu untuk kamu berikan kepada Kami.</p>

<p>Kamu dengan ini telah sepakat dan menyetujui bahwa MTICKET memiliki hak dan kewenangan penuh berdasarkan kebijakan Kami sendiri, untuk menghapus, tidak memproses, masukan ke daftar hitam, blokir dan/atau dengan metode dan cara-cara yang Kami anggap perlu untuk menangani setiap akun Event Creator yang Kami anggap telah melanggar Ketentuan Penggunaan ini, melakukan tindak pidana, melanggar ketentuan peraturan perundang-undangan, ketertiban umum, keasusilaan, penipuan, penyalahgunaan, kelalaiaan, kealpaan dan/atau berdasarkan kebijakan Kami yang dapat dipertanggungjawabkan.</p>

<h3>D. Konten Event</h3>

<p>Event Creator yang telah membuat akun pada Situs kami, dapat membuat Event dengan tunduk pada syarat dan ketentuan dalam Ketentuan Penggunaan ini, norma susila, ketertiban umum dan peraturan perundang-undangan yang berlaku.</p>

<p>Event Creator wajib menyediakan kepada Kami secara cuma-cuma tanpa imbalan dalam bentuk apapun semua informasi dan data mengenai Event dengan data dan informasi yang benar. valid, legal, sah, akurat dan tidak melanggar hak kekayaan intelektual pihak lain dalam bentuk apapun. Event Creator dilarang membuat deskripsi mengenai Event yang melanggar ketentuan peraturan perundang-undangan, ketertiban umum, kesusilaan, norma yang berlaku, seperti namun tidak terbatas pada provokasi terhadap suku, agama, ras dan antar golongan (SARA) dan/atau golongan tertentu, pemerasan, pornografi, vulgar, menyudutkan orang atau golongan tertentu, pengancaman, penghinaan, pencemaran nama baik, kekerasan, menakut-nakuti, menyesatkan, bohong, seruan yang menimbulkan rasa kebencian atau permusuhan yang memecah belah, dan/atau seruan untuk melanggar hukum yang berlaku.</p>

<p>Event yang Event Creator selenggarakan dilarang mengandung unsur, baik dalam bentuk penamaan, isi dari Event, kegiatan yang berada dalam Event, tempat dari Event, dan/atau segala bentuk yang termasuk dari unsur-unsur Event tersebut yang berkaitan dan menjadi suatu kesatuan yang saling terkait dalam Event tersebut baik secara langsung maupun tidak langsung, dimana termasuk dari unsur berupa pelanggaran dari ketentuan peraturan perundang-undangan, pencucian uang, ketertiban umum, kesusilaan, norma yang berlaku, seperti namun tidak terbatas pada bentuk perjudian, prostitusi, provokasi terhadap suku, agama, ras dan antar golongan (SARA) dan/atau golongan tertentu, pemerasan, pornografi, pengancaman, penghinaan, pencemaran nama baik, kekerasan, menakut-nakuti, menyesatkan, bohong, seruan yang menimbulkan rasa kebencian atau permusuhan yang memecah belah, yang seluruh kegiatannya hanya berbentuk pengumpulan uang dan/atau barang tanpa adanya kegiatan acara lain, dan/atau seruan untuk melanggar hukum yang berlaku.</p>

<p>Event Creator menyatakan dan menjamin kepada Kami bahwa:</p>

<p>Seluruh informasi dan data yang disediakan kepada Kami, baik berupa poster, gambar, kata-kata, istilah dan/atau segala bentuk ciptaan lainnya yang merupakan hak kekayaan intelektual merupakan hak dan kewenangan dari Event Creator untuk digunakan baik secara ekonomis maupun non komersial bagi kepentingan Event oleh Event Creator;</p>

<p>Event yang diselenggarakan adalah hak, milik, kepunyaan, dan kewenangan penuh dan/atau merupakan kuasa dengan telah diterimanya semua bentuk persetujuan yang diperlukan untuk Event Creator dalam mewakili penyelenggaraan Event;</p>

<p>Penyelenggaraan Event berserta isinya dan tunduknya Event Creator pada perjanjian ini tidak melanggar ketentuan apapun, baik berdasarkan peraturan perundang-undangan, perjanjian lain, perintah pengadilan, perintah badan pemerintahan dan kewajiban-kewajiban apapun dimana Event Creator terikat untuk tunduk pada ketentuan tersebut;</p>

<p>Event Creator bertanggungjawab penuh atas keseluruhan Event termasuk pada isinya, sampingannya ataupun unsur-unsurnya yang terkait dan menjadi satu kesatuan baik secara langsung maupun tidak langsung pada Event tidak melanggar Ketentuan Penggunaan ini, peraturan perundang-undangan, keasusilaan, ketertiban umum, hak kekayaan intelektual pihak lain dan ketentuan-ketentuan lainnya yang harus dipatuhi;</p>

<p>Event Creator telah memperoleh segala bentuk perizinan, persetujuan, rekomendasi, dan/atau segala bentuk dokumen-dokumen lainnya dalam pelaksanaan Event yang diselenggarakan;</p>

<p>Isi dari Event, baik bentuk kegiatan, pengisi kegiatan, jenis kegiatan, tipe kegiatan, acara kegiatan Event termasuk jenis dan tipe Tiket dan segala bentuk yang berkaitan dengan isi Event yang dibuat serta diisi pada sistem MTICKET adalah benar dan sesuai dengan kenyataan yang ada. Dalam hal terjadi perubahan mengenai Event dalam bentuk apapun, termasuk namun tidak terbatas pada tempat, jenis, waktu, kegiatan, sifat komersil menjadi non komersil begitupula sebaliknya, tipe dan klasifikasi Tiket dan perubahan lainnya, Event Creator wajib untuk memberitahu kepada MTICKET dan/atau Pembeli Tiket terhadap perubahan tersebut.</p>

<p>Event Creator dengan ini setuju untuk bertanggungjawab secara penuh dan melepaskan dan membebaskan MTICKET dari segala bentuk tanggung jawab, ganti kerugian, tuntutan, gugatan, klaim hak, permintaan hak dari pihak manapun dan/atau segala bentuk kewajiban yang harus ditanggung akibat dari pelanggaran Ketentuan Penggunaan ini, pelanggaran peraturan perundang-undangan, pelanggaran norma sosial, keasusilaan, ketertiban umum, dan/atau pelanggaran atas hak-hak pihak lain yang merasa haknya dilanggar oleh akibat pelaksanaan Event dan/atau pelanggaran dari larangan, pernyataan dan jaminan, kewajiban dan segala bentuk ketentuan dari Ketentuan Penggunaan ini.</p>

<p>Event Creator bertanggung jawab penuh atas seluruh izin, persetujuan, dispensasi, perintah, lisensi, pajak, pungutan, persetujuan penggunaan hak kekayaan intelektual dan/atau dokumen dalam bentuk apapun yang diperlukan berdasarkan ketentuan peraturan perundang-undangan termasuk kebijakan pemerintahan, yang diperlukan untuk keberlangsungan dan penyelenggaran Event tersebut.</p>

<p>Event Creator dengan ini telah sepakat dan menyetujui bahwa MTICKET memiliki hak dan kewenangan penuh berdasarkan kebijakan Kami sendiri, untuk menolak, menghapus, tidak memproses, masukan ke daftar hitam, blokir, menghentikan kerja sama secara sepihak, menuntut ganti rugi, menuntut berbagai hak untuk memulihkan hak yang telah dilanggar dan/atau dengan metode dan cara-cara yang Kami anggap perlu untuk menangani setiap Event yang Kami anggap telah melanggar Ketentuan Penggunaan ini, melakukan tindak pidana, melanggar ketentuan peraturan perundang-undangan, ketertiban umum, keasusilaan, penipuan, penyalahgunaan, kelalaiaan, kealpaan dan/atau berdasarkan kebijakan Kami yang dapat dipertanggungjawabkan.</p>

<h3>E. Ketentuan Pembayaran</h3>

<p>Setiap Event yang diselenggarakan oleh Event Creator dalam Platform kami, maka Kami berhak atas Biaya Jasa sebesar sebagaimana tercantum di&nbsp;<a href="https://www.mticket.com/panduan" rel="noopener noreferrer" target="_blank">https://www.MTICKET.com/panduan</a>&nbsp;.</p>

<p>Sebelum melakukan penagihan atas uang hasil penjualan Tiket Event yang terjual melalui sistem MTICKET, Event Creator wajib untuk mengisi dan menyediakan data dan informasi yang diperlukan oleh Kami sekurang-kurangnya sebagaimana tercantum di&nbsp;<a href="https://www.mticket.com/panduan" rel="noopener noreferrer" target="_blank">https://www.MTICKET.com/panduan</a>&nbsp;.</p>

<p>Event Creator dapat melakukan penagihan atas uang hasil penjualan Tiket Event yang terjual melalui sistem MTICKET setelah Event berakhir dan telah memenuhi semua syarat dan ketentuan yang berlaku.</p>

<p>MTICKET baru akan melakukan proses pembayaran atas tagihan sebagaimana dimaksud pada ayat (2) dan (3) di atas maksimal 10 (sepuluh) hari kerja sejak diterimanya dan telah lengkapnya seluruh persyaratan yang diperlukan yang disediakan oleh Event Creator.</p>

<p>Pembayaran atas hasil penjualan Tiket akan dilakukan oleh MTICKET dengan cara transfer dana ke rekening Event Creator berdasarkan data dan informasi yang telah diisi oleh Event Creator. Segala bentuk kesalahan dari pengisian data dan informasi rekening Event Creator yang menyebabkan keterlambatan, kegagalan, kerugian, pengurangan dan segala bentuk akibat yang timbul akibat dari hal tersebut, bukan merupakan tanggung jawab dari MTICKET sehingga Event Creator setuju dan memahami untuk melepaskan dan membebaskan MTICKET atas tanggung jawab terhadap hal tersebut. Oleh karena itu, Event Creator wajib secara seksama, akurat, teliti, cermat, hati-hati dan benar terhadap rekening milik Event Creator.</p>

<p>Event Creator menjamin dan bertanggung jawab penuh bahwa data dan informasi rekening merupakan rekening yang sah, valid, legal dan milik dari Event Creator yang mewakili Event tersebut. Untuk menghindari keragu-raguan, Event Creator melepaskan dan membebaskan MTICKET dan akan menanggung segala bentuk tuntutan, gugatan, permintaan, perintah dan klaim oleh pihak manapun termasuk oleh Event Creator sendiri atas hasil penjualan Tiket yang MTICKET kirim pada rekening berdasarkan data dan informasi yang Event Creator isi tersebut.</p>

<p>Event Creator bertanggung jawab penuh atas seluruh pajak, pungutan, kontribusi, retribusi, biaya, bunga dan/atau tagihan dalam bentuk apapun yang menjadi kewajiban yang harus dilakukan dalam pelaksanaan dan penyelenggaraan Event.</p>

<p>Pembayaran atas penjualan Tiket Event yang diberikan kepada Event Creator berdasarkan laporan penjualan yang tercantum dalam sistem MTICKET, akan dibayarkan setelah dipotong dengan Biaya Jasa kami, termasuk pajak pertambahan nilai (PPN).</p>

<p>Kecuali ditentukan lain dalam perjanjian ini, semua jenis pajak, biaya ataupun pungutan lainnya, baik yang ada saat ini maupun yang ada dikemudian hari, yang wajib dibayarkan ke pemerintah yang berkaitan dengan transaksi berdasarkan perjanjian ini, wajib ditanggung oleh Event Creatorajak sesuai ketentuan perundang-undangan yang berlaku.</p>

<p>Dalam hal Event Creator tidak melakukan penagihan haknya, termasuk hasil penjualan Tiket, yang berada pada Kami selambat-lambatnya 30 hari kalender sejak berakhirnya Event, maka dengan ini Event Creator telah menyetujui untuk memberikan hak tersebut kepada Kami, dan hak tersebut menjadi hak dan milik MTICKET sepenuhnya.</p>

<p>F. Perubahan dan Pembatalan Acara</p>

<p>Dalam hal terjadi perubahan kegiatan Event yang diakibatkan oleh satu dan lain hal, maka Event Creator wajib memberitahukan kepada Kami dan Pembeli secara resmi paling lambat 7 (tujuh) hari sebelum perubahan kegiatan Event tersebut.</p>

<p>Dalam hal terjadi pembatalan Event, MTICKET tetap berhak atas Biaya Jasa yang telah dilakukannya dan biaya-biaya lainnya yang telah dikeluarkan Pihak Kedua yang berkaitan dengan pelaksanaan kerja sama, termasuk biaya administrasi bank untuk transfer pengembalian uang kepada Pembeli ( refund) dan biaya-biaya lainnya, yang akan ditagihkan kepada Event Creator.</p>

<p>Dalam hal terjadi pembatalan Event, Event Creator bertanggung jawab secara penuh untuk mengembalikan uang hasil pembelian Tiket oleh Pembeli kepada Pembeli melalui MTICKET dengan melakukan pembayaran biaya-biaya sebagaimana di maksud Huruf (F) poin (2) di atas dengan ditambah dengan total uang pengembalian Tiket, dimana total tersebut akan dikurangkan dengan uang hasil pembelian Tiket dan kekurangan uang tersebut wajib dibayar oleh Event Creator paling lambat 7 (tujuh) hari melalui rekening Kami yang akan kami berikan berserta jumlah yang harus dibayar kepada Event Creator.</p>

<p>Jumlah uang pengembalian atas pembatalan Event kepada Pembeli adalah sebesar 100% (seratus persen) dari harga Tiket dan tidak termasukconvinience fee yang sudah dipotong oleh pihak bank dan payment gateway (jika transaksi dilakukan dengan fasilitas pembayaran dari perusahaan payment gateway) atau biaya-biaya lainnya yang akan ditanggung oleh Event Creator, sesuai sebagaimana dimaksud dalam Huruf (F) poin (2) dan (3) di atas.</p>

<h3>G. Perizinan</h3>

<p>Dengan tergantung pada kepatuhan Pengguna pada Ketentuan Penggunaan, kami memberikan Pengguna ijin yang terbatas, non-eksklusif, tidak dapat dipindahtangankan, tidak dapat dialihkan, tidak dapat disublisensikan, ijin yang dapat ditarik untuk mengunduh dan memasang salinan Situs pada suatu perangkat bergerak tunggal yang Pengguna miliki atau kontrol dan menjalankan salinan Situs semata-mata untuk kebutuhan pribadi, non-komersial Pengguna sendiri.</p>

<p>Pengguna tidak diperkenankan (i) menyalin, memodifikasi, mengadaptasi, menerjemahkan, membuat karya turunan dari, mendistribusikan, memberikan lisensi, menjual, mengalihkan, menampilkan di muka umum, membuat ulang, mentransmisikan, memindahkan, menyiarkan, menguraikan, atau membongkar bagian manapun dari atau dengan cara lain yang mungkin mengeksploitasi Situs, kecuali sebagaimana diperbolehkan dalam Ketentuan Penggunaan ini, (ii) memberikan lisensi, mensublisensikan, menjual, menjual kembali, memindahkan, mengalihkan, mendistribusikan atau mengeksploitasi secara komersial atau membuat tersedia kepada pihak ketiga Situs dan / atau perangkat lunak dengan cara; (iii) menciptakan &quot;link&quot;internet ke Situs atau &quot;frame&quot; atau &quot;mirror&quot; setiap perangkat lunak pada server lain atau perangkat nirkabel atau yang berbasis internet; (iv) merekayasa ulang atau mengakses perangkat lunak kami untuk (a) membangun produk atau layanan tandingan, (b) membangun produk dengan menggunakan ide, fitur, fungsi atau grafis sejenis Situs, atau (c) menyalin ide, fitur, fungsi atau grafis Situs, (v) meluncurkan program otomatis atau script, termasuk, namun tidak terbatas pada, web spiders, web crawlers, web robots, web ants, web indexers, bots, virus atau worm, atau segala program apapun yang mungkin membuat beberapa permintaan server per detik, atau menciptakan beban berat atau menghambat operasi dan/atau kinerja Situs, (vi) menggunakan robot, spider, pencarian situs/Situs pengambilan kembali, atau perangkat manual atau otomatis lainnya atau proses untuk mengambil, indeks, &quot;tambang data&quot; (data mine), atau dengan cara apapun memperbanyak atau menghindari struktur navigasi atau presentasi dari Situs atau isinya; (vii) menerbitkan, mendistribusikan atau memperbanyak dengan cara apapun materi yang dilindungi hak cipta, merek dagang, atau informasi yang dimiliki lainnya tanpa memperoleh persetujuan terlebih dahulu dari pemilik hak milik, (viii) menghapus setiap hak cipta, merek dagang atau pemberitahuan hak milik lainnya yang terkandung dalam Situs. Tidak ada lisensi atau hak yang diberikan kepada Pengguna dengan implikasi berdasarkan hak kekayaan intelektual dimiliki atau dikendalikan oleh kami atau pemberi lisensi kami, kecuali untuk lisensi dan hak tersebut secara tegas diberikan dalam Ketentuan Penggunaan ini.</p>

<p>Pengguna tidak diperkenankan (i) menyalin, memodifikasi, mengadaptasi, menerjemahkan,membuat karya turunan dari, mendistribusikan, memberikan lisensi, menjual, mengalihkan, menampilkan di muka umum, membuat ulang, mentransmisikan, memindahkan, menyiarkan, menguraikan, atau membongkar bagian manapun dari atau dengan cara lain yang mungkin mengeksploitasi Situs, kecuali sebagaimana diperbolehkan dalam Ketentuan Penggunaan ini, (ii) memberikan lisensi, mensublisensikan, menjual, menjual kembali, memindahkan, mengalihkan, mendistribusikan atau mengeksploitasi secara komersial atau membuat tersedia kepada pihak ketiga Situs dan / atau perangkat lunak dengan cara; (iii) menciptakan &quot;link&quot; internet ke Situs atau &quot;frame&quot; atau &quot;mirror&quot; setiap perangkat lunak pada server lain atau perangkat nirkabel atau yang berbasis internet; (iv) merekayasa ulang atau mengakses perangkat lunak kami untuk (a) membangun produk atau layanan tandingan, (b) membangun produk dengan menggunakan ide, fitur, fungsi atau grafis sejenis Situs, atau (c) menyalin ide, fitur, fungsi atau grafis Situs, (v) meluncurkan program otomatis atau script, termasuk, namun tidak terbatas pada, web spiders, web crawlers, web robots, web ants, web indexers, bots, virus atau worm, atau segala program apapun yang mungkin membuat beberapa permintaan server per detik, atau menciptakan beban berat atau menghambat operasi dan/atau kinerja Situs, (vi) menggunakan robot, spider, pencarian situs/Situs pengambilan kembali, atau perangkat manual atau otomatis lainnya atau proses untuk mengambil, indeks, &quot;tambang data&quot; (data mine), atau dengan cara apapun memperbanyak atau menghindari struktur navigasi atau presentasi dari Situs atau isinya; (vii) menerbitkan, mendistribusikan atau memperbanyak dengan cara apapun materi yang dilindungi hak cipta, merek dagang, atau informasi yang dimiliki lainnya tanpa memperoleh persetujuan terlebih dahulu dari pemilik hak milik, (viii) menghapus setiap hak cipta, merek dagang atau pemberitahuan hak milik lainnya yang terkandung dalam Situs. Tidak ada lisensi atau hak yang diberikan kepada Pengguna dengan implikasi berdasarkan hak kekayaan intelektual dimiliki atau dikendalikan oleh kami atau pemberi lisensi kami, kecuali untuk lisensi dan hak tersebut secara tegas diberikan dalam Ketentuan Penggunaan ini.</p>

<p>Pengguna tidak diperkenankan (i) menyalin, memodifikasi, mengadaptasi, menerjemahkan, membuat karya turunan dari, mendistribusikan, memberikan lisensi, menjual, mengalihkan, menampilkan di muka umum, membuat ulang, mentransmisikan, memindahkan, menyiarkan, menguraikan, atau membongkar bagian manapun dari atau dengan cara lain yang mungkin mengeksploitasi Situs, kecuali sebagaimana diperbolehkan dalam Ketentuan Penggunaan ini, (ii) memberikan lisensi, mensublisensikan, menjual, menjual kembali, memindahkan, mengalihkan, mendistribusikan atau mengeksploitasi secara komersial atau membuat tersedia kepada pihak ketiga Situs dan / atau perangkat lunak dengan cara; (iii) menciptakan &quot;link&quot; internet ke Situs atau &quot;frame&quot; atau &quot;mirror&quot; setiap perangkat lunak pada server lain atau perangkat nirkabel atau yang berbasis internet; (iv) merekayasa ulang atau mengakses perangkat lunak kami untuk (a) membangun produk atau layanan tandingan, (b) membangun produk dengan menggunakan ide, fitur, fungsi atau grafis sejenis Situs, atau (c) menyalin ide, fitur, fungsi atau grafis Situs, (v) meluncurkan program otomatis atau script, termasuk, namun tidak terbatas pada, web spiders, web crawlers, web robots, web ants, web indexers, bots, virus atau worm, atau segala program apapun yang mungkin membuat beberapa permintaan server per detik, atau menciptakan beban berat atau menghambat operasi dan/atau kinerja Situs, (vi) menggunakan robot, spider, pencarian situs/Situs pengambilan kembali, atau perangkat manual atau otomatis lainnya atau proses untuk mengambil, indeks, &quot;tambang data&quot; (data mine), atau dengan cara apapun memperbanyak atau menghindari struktur navigasi atau presentasi dari Situs atau isinya; (vii) menerbitkan, mendistribusikan atau memperbanyak dengan cara apapun materi yang dilindungi hak cipta, merek dagang, atau informasi yang dimiliki lainnya tanpa memperoleh persetujuan terlebih dahulu dari pemilik hak milik, (viii) menghapus setiap hak cipta, merek dagang atau pemberitahuan hak milik lainnya yang terkandung dalam Situs. Tidak ada lisensi atau hak yang diberikan kepada Pengguna dengan implikasi berdasarkan hak kekayaan intelektual dimiliki atau dikendalikan oleh kami atau pemberi lisensi kami, kecuali untuk lisensi dan hak tersebut secara tegas diberikan dalam Ketentuan Penggunaan ini.</p>

<p>Pengguna tidak diperkenankan (i) menyalin, memodifikasi, mengadaptasi, menerjemahkan, membuat karya turunan dari, mendistribusikan, memberikan lisensi, menjual, mengalihkan, menampilkan di muka umum, membuat ulang, mentransmisikan, memindahkan, menyiarkan, menguraikan, atau membongkar bagian manapun dari atau dengan cara lain yang mungkin mengeksploitasi Situs, kecuali sebagaimana diperbolehkan dalam Ketentuan Penggunaan ini, (ii) memberikan lisensi, mensublisensikan, menjual, menjual kembali, memindahkan, mengalihkan, mendistribusikan atau mengeksploitasi secara komersial atau membuat tersedia kepada pihak ketiga Situs dan / atau perangkat lunak dengan cara; (iii) menciptakan &quot;link&quot; internet ke Situs atau &quot;frame&quot; atau &quot;mirror&quot; setiap perangkat lunak pada server lain atau perangkat nirkabel atau yang berbasis internet; (iv) merekayasa ulang atau mengakses perangkat lunak kami untuk (a) membangun produk atau layanan tandingan, (b) membangun produk dengan menggunakan ide, fitur, fungsi atau grafis sejenis Situs, atau (c) menyalin ide, fitur, fungsi atau grafis Situs, (v) meluncurkan program otomatis atau script, termasuk, namun tidak terbatas pada, web spiders, web crawlers, web robots, web ants, web indexers, bots, virus atau worm, atau segala program apapun yang mungkin membuat beberapa permintaan server per detik, atau menciptakan beban berat atau menghambat operasi dan/atau kinerja Situs, (vi) menggunakan robot, spider, pencarian situs/Situs pengambilan kembali, atau perangkat manual atau otomatis lainnya atau proses untuk mengambil, indeks, &quot;tambang data&quot; (data mine), atau dengan cara apapun memperbanyak atau menghindari struktur navigasi atau presentasi dari Situs atau isinya; (vii) menerbitkan, mendistribusikan atau memperbanyak dengan cara apapun materi yang dilindungi hak cipta, merek dagang, atau informasi yang dimiliki lainnya tanpa memperoleh persetujuan terlebih dahulu dari pemilik hak milik, (viii) menghapus setiap hak cipta, merek dagang atau pemberitahuan hak milik lainnya yang terkandung dalam Situs.Tidak ada lisensi atau hak yang diberikan kepada Pengguna dengan implikasi berdasarkan hak kekayaan intelektual dimiliki atau dikendalikan oleh kami atau pemberi lisensi kami, kecuali untuk lisensi dan hak tersebut secara tegas diberikan dalam Ketentuan Penggunaan ini.</p>

<h3>H. Hak Kekayaan Intelektual</h3>

<p>Kami menyediakan Kamu dengan konten seperti suara, foto, gambar, video atau materi lain yang terkandung dalam iklan disponsori atau informasi. Bahan ini dapat dilindungi oleh hak cipta, merek dagang atau hak kekayaan intelektual lainnya dan undang- undang. Kamu dapat menggunakan bahan ini hanya secara tegas diizinkan oleh MTICKET dan tidak akan menyalin, mengirimkan atau membuat karya turunan dari materi tersebut tanpa izin tertulis dari MTICKET.</p>

<p>Kamu mengakui dan setuju bahwa Kamu tidak akan mengunduh, posting, memperbanyak atau mendistribusikan konten apapun atau melalui Platform yang dilindungi oleh hak cipta atau hak milik lainnya dari pihak ketiga, tanpa memperoleh izin dari pemilik hak tersebut. Setiap konten eksklusif hak cipta atau lainnya didistribusikan atau melalui Platform dengan persetujuan dari pemilik harus berisi hak cipta yang sesuai atau pemberitahuan hak kepemilikan lainnya. Pengajuan atau distribusi konten eksklusif hak cipta atau lainnya yang tidak sah adalah ilegal dan bisa dikenai tanggung jawab pribadi atau penuntutan pidana.</p>

<h3>I. Jaminan</h3>

<p>Kami tidak memberikan pernyataan, jaminan atau garansi untuk dapat diandalkannya, ketepatan waktu, kualitas, kesesuaian, ketersediaan, akurasi atau kelengkapan dari layanan, Situs kami dan/atau Platform kami, termasuk namun tidak terbatas pada Layanan yang diperoleh atau berasal dari Mitra kami melalui penggunaan Platform tersebut. Kami tidak menyatakan atau menjamin bahwa (a) penggunaan Platform akan aman, tepat waktu, tanpa gangguan atau terbebas dari kesalahan atau beroperasi dengan kombinasi dengan perangkat keras lain, perangkat lunak, sistem atau data, (b) layanan akan memenuhi kebutuhan atau harapan Kamu, (c) setiap data yang tersimpan akan akurat atau dapat diandalkan, (d) kualitas produk, layanan, informasi, atau bahan-bahan lain yang dibeli atau diperoleh oleh Kamu melalui Platform akan memenuhi kebutuhan atau harapan Kamu, (e) kesalahan atau kecacatan dalam Platform akan diperbaiki, atau (f) Platform atau server(-server) yang menyediakan Platform terbebas dari virus atau komponen berbahaya lainnya. Layanan disediakan untuk Kamu terbatas hanya pada dasar &quot;sebagaimana adanya&quot;. Semua kondisi, pernyataan dan jaminan, baik tersurat, tersirat, yang diwajibkan oleh undang-undang atau sebaliknya, termasuk, namun tidak terbatas pada, jaminan yang tersirat mengenai jual beli, kesesuaian untuk tujuan tertentu, atau tidak adanya pelanggaran hak pihak ketiga, dengan ini dikecualikan dan dikesampingkan dengan batas tertinggi dan maksimum. Kamu mengakui dan menyetujui bahwa seluruh risiko yang timbul dari penggunaan Platform oleh Kamu tetap semata-mata dan sepenuhnya ada pada Kamu dan Kamu tidak akan memiliki hak untuk meminta ganti rugi apapun dari Kami.</p>

<h3>J. Larangan</h3>

<p>Sebagai kondisi penggunaan platform, Kamu menjamin bahwa Kamu tidak akan menggunakan Platform ini untuk tujuan apapun yang melanggar hukum atau ilegal di bawah hukum untuk saat ini berlaku dalam atau di luar Indonesia atau dilarang oleh syarat dan ketentuan dan / atau Ketentuan Penggunaan ini termasuk secara spesifik dan/atau tersirat. Selain itu, Platform tidak boleh digunakan dengan cara apapun, yang dapat merusak, melumpuhkan, membebani atau mengganggu penggunaan pihak lain dan/atau pengguna Platform. Kamu harus patuh dan taat untuk memperoleh atau mencoba untuk memperoleh bahan atau informasi melalui cara yang dibuat dan tersedia atau disediakan melalui Platform ini dengan iktikad baik.</p>

<h3>K. Pelanggaran</h3>

<p>Tanpa mengurangi aturan lain yang tersedia pada Ketentuan Penggunaan ini, peraturan Kami atau berdasarkan hukum yang berlaku, Kami dapat membatasi aktivitas anda, memperingatkan Pembeli ataupun pihak lain dari tindakan anda, menurunkan dan/atau membatalkan Event Kamu, sifatnya sementara/selamanya menangguhkan atau menghentikan pendaftaran dan/atau Event Kamu, termasuk namun tidak terbatas pada akun dan/atau Event anda, dan/atau menolak untuk memberikan akses ke Platform, dan/atau tindakan-tindakan lainnya berdasarkan kebijakan Kami, jika:</p>

<p>Kamu melanggar Ketentuan Penggunaan ini, peraturan perundang-undangan dan/atau dokumen lain yang terkait;</p>

<p>data dan/atau informasi yang diberikan oleh Kamu tidak sah, valid, legal, palsu dan/atau tidak dapat terverifikasi oleh Kami; atau</p>

<p>Kami percaya bahwa tindakan Kamu mungkin dapat melanggar hak pihak ketiga atau melanggar hukum yang berlaku atau mengakibatkan kewajiban bagi kita, Kamu dan / atau pengguna lainnya termasuk calon Pembeli.</p>

<p>Dengan tunduk dengan peraturan lainnya dalam Ketentuan Penggunaan ini, dalam hal Event Kamu dibatalkan oleh MTICKET karena melanggar salah satu dari Ketentuan Penggunaan ini dan/atau peraturan perundang-undangan yang berlaku, maka uang yang terkumpul akan MTICKET berikan kepada Pembeli.</p>

<h3>L. Batasan Tanggung Jawab</h3>

<p>Kami tidak bertanggung jawab atas setiap cidera, kematian, kerusakan atau kerugian yang terjadi di Event dan/atau penggunaan Platform. Kami juga tidak bertanggung jawab atas kesalahan, termasuk pelanggaran, atau tindakan kriminal yang dilakukan oleh Pembeli atapun pihak lain yang berada dalam tempat Event berlangsung selama pelaksanaan Event, termasuk Event Creator sendiri.</p>

<p>Kami tidak bertanggung jawab dan Kamu menjamin dan membebaskan Kami, Mitra kami, dan perusahaan afiliasi Kami dari tanggung jawab atas setiap kerugian,tuntutan, gugatan dan/atau permintaan hak-hak apapun oleh Kamu, Pembeli, pengunjung acara dan/atau pihak ketiga atas penyalahgunaan, fraud, perbuatan curang dan/atau tindakan-tindakan lainnya akibat dari penyebaran informasi dan/atau data Event, termasuk data/informasi Tiket Event, yang Kamu lakukan sendiri dan/atau akibat dari kelalaian, kealpaan dan/atau kesengajaan Kamu. Oleh karena itu, Kamu diwajibkan untuk menjaga dan tidak menyebarkan informasi dan data pribadi Kamu sendiri, termasuk akun Kamu.</p>

<p>Setiap tuntutan terhadap Kami dalam hal apapun oleh Kamu, akan dibatasi dengan jumlah total yang sebenarnya dibayar oleh dan/atau terutang pada Kamu ketika menggunakan layanan Kami selama peristiwa yang menimbulkan klaim tersebut. Dalam hal apapun Kami dan/atau pemberi lisensi Kami tidak akan bertanggung jawab kepada Kamu atau siapa pun atas biaya, bunga, kerusakan atau kerugian dalam segala jenis atau bentuk (termasuk cedera pribadi, gangguan emosi dan hilangnya data, barang, pendapatan, keuntungan, penggunaan atau keuntungan ekonomi lainnya). Kami tidak akan bertanggung jawab atas kerugian, kerusakan atau cedera yang mungkin ditimbulkan oleh atau disebabkan oleh Kamu pada saar Event berlangsung ataupun dalam rangka pelaksanaan perjanjian ini atau pada setiap orang untuk siapa Kamu telah memesan layanan, termasuk namun tidak terbatas pada kerugian, kerusakan atau cedera yang timbul dari, atau dengan cara apapun sehubungan dengan layanan dan/atau Platform, termasuk namun tidak terbatas pada penggunaan atau ketidakmampuan untuk menggunakan layanan dan/atau Platform dan/atau Situs Kami.</p>

<p>Kamu secara tegas mengesampingkan dan melepaskan kami dari setiap dan semua kewajiban, tuntutan atau kerusakan yang timbul dari atau dengan cara apapun sehubungan dengan Pembeli, mitra Kamu, Mitra, pengunjung Event, pihak yang berada pada Event dan/atau Event. Kami dan perusahaan afiliasi Kami tidak akan menjadi pihak dalam sengketa, negosiasi sengketa antara Kamu dengan pihak manapun. Tanggung jawab untuk keputusan yang Kamu buat atas Event merupakan tanggung jawab dan melekat seutuhnya dengan dan pada Kamu. Kamu secara tegas mengesampingkan dan melepaskan kami dari setiap dan semua kewajiban, tuntutan, penyebab tindakan, atau kerusakan yang timbul dari penggunaan Platform, pelaksanaan Event, perangkat lunak dan/atau Platform, atau dengan cara apapun terkait dengan Kami dan Mitra Kami yang diperkenalkan kepada Kamu melalui Platform.</p>

<p>Kami akan mengambil langkah yang sifatnya wajar untuk mencegah penipuan internet dan memastikan data yang dikumpulkan oleh Kami dan disimpan supaya aman. Namun, kami tidak bertanggung jawab dalam hal dari pelanggaran di server komputer Kamu, Kami tidak bertanggung jawab sebagai pihak ketiga.</p>

<h3>M. Ganti Rugi</h3>

<p>Dengan menggunakan layanan Kami ini, Kamu setuju bahwa Kamu akan membela, memberikan ganti rugi dan membebaskan Kami, pemberi lisensi, afiliasi, dan masing-masing dari petugas, direktur, komisaris, karyawan, pengacara dan agen kami dari dan terhadap setiap dan semua klaim, biaya, kerusakan, kerugian, kewajiban dan biaya (termasuk biaya dan ongkos pengacara) yang timbul dari atau sehubungan dengan: (a) penggunaan layanan pada Situs Kami dan/atau Platform oleh Kamu, hubungan Kamu dengan Pembeli, penyedia pihak ketiga, mitra, pemasang iklan dan/atau sponsor, atau (b) pelanggaran atas atau tidak dipatuhinya salah satu Ketentuan Penggunaan atau peraturan perundang-undangan yang berlaku, baik yang disebutkan di sini atau tidak atau (c) pelanggaran Kamu terhadap hak-hak pihak ketiga, termasuk mitra pihak ketiga dan Mitra Kami, atau (d) penggunaan atau penyalahgunaan layanan Platform Kami. Kewajiban pembelaan dan pemberian ganti rugi ini akan tetap berlaku walaupun Ketentuan Penggunaan dan penggunaan Situs oleh Kamu dan Event telah berakhir.</p>

<h3>N. Ketentuan Lain</h3>

<p>Jika ada ketentuan dalam Ketentuan Penggunaan ini yang ditentukan secara tidak sah atau tidak dapat diterapkan secara keseluruhan atau sebagian, cacat atau harus diterjemahkan hanya untuk ketentuan tersebut atau bagian dari ketentuan tersebut dan sisa bagian dari ketentuan tersebut dan semua ketentuan lain dari syarat ini kondisi akan terus berada dan berlaku sepenuhnya, sedangkan ketentuan tersebut akan Kami sesuaikan sehingga dapat dilaksanakan dan sepenuhnya disetujui oleh Kamu.</p>

<p>Syarat dan ketentuan akan diatur oleh dan ditafsirkan sesuai dengan hukum Republik Indonesia. Penyelesaian sengketa yang terjadi di antara Kamu dan Kami akan diselesaikan secara musyarawah selama 30 (hari) dan jika terjadi kesepakatan akan diselesaikan melalui dan tunduk pada peraturan yang berlaku pada Badan Abritrase Nasional Indonesia.</p>

<p>Dari waktu ke waktu, Kami dapat secara sepihak merubah, merevisi, memperbaiki, menghapus, menambahkan dan/atau merubah dengan bentuk apapun dari syarat dan ketentuan yang tertuang dalam Ketentuan Penggunaan ini berdasarkan kebijakan dan kewenangan Kami.</p>

<p>Halo, selamat datang di situs&nbsp;<a href="http://www.mticket.asia/" rel="noopener noreferrer" target="_blank">www.mticket.asia</a>&nbsp;yang dikelola dan dimiliki oleh PT EDRUS EXPO ANUGERAH, selaku pemilik brand MTICKET (&ldquo;Situs&rdquo;). PT EDRUS EXPO ANUGERAH adalah perseroan terbatas yang bergerak di bidang teknologi yaitu penyediaan piranti lunak (software) berupa platform untuk memudahkan dan membuat pengalaman penggunaan terbaik dalam menikmati event bagi kamu dan event creator (untuk selanjutnya disebut &ldquo;MTICKET&rdquo; atau &ldquo;Kami&rdquo;). Setiap orang atau badan hukum yang menggunakan, mengakses, memanfaatkan dan/atau membuat akun di Situs Kami (untuk selanjutnya disebut &ldquo;Kamu&rdquo;) dengan ini dianggap telah memahami, membaca, menerima dan setuju akan ketentuan penggunaan Situs dan layanan MTICKET, sebagaimana akan diuraikan di bawah ini (untuk selanjutnya disebut &ldquo;Ketentuan Penggunaan&rdquo;).</p>

<p>Ketentuan Penggunaan ini adalah perjanjian yang sah dan mengikat antara Kamu dan MTICKET. Silahkan untuk membatalkan akun Kamu dan/atau keluar dari Situs serta tidak menggunakan, mengakses dan/atau memanfaatkan Situs ini jika Kamu tidak setuju atau tidak ingin terikat dengan Ketentuan Penggunaan ini.</p>

<p>MOHON MEMERIKSA KETENTUAN PENGGUNAAN DAN KEBIJAKAN PRIVASI MTICKET DENGAN SEKSAMA SEBELUM MENGGUNAKAN SITUS DAN LAYANAN MTICKET UNTUK PERTAMA KALI. DENGAN MENDAFTAR, MEMBUAT AKUN DAN/ATAU MENGGUNAKAN SITUS ATAU LAYANAN MTICKET, KAMU SECARA PRIBADI DAN/ATAU BADAN HUKUM YANG KAMU WAKILI TELAH MEMAHAMI DAN SETUJU UNTUK TUNDUK SERTA TERIKAT PADA SELURUH SYARAT DAN KETENTUAN PENGGUNAAN INI DAN KEBIJAKAN PRIVASI MTICKET. DENGAN INI KAMU MENYATAKAN SERTA MENJAMIN KEPADA MTICKET BAHWA KAMU ADALAH PERORANGAN ATAU PERWAKILAN BADAN HUKUM YANG SAH DAN BERHAK UNTUK BERTINDAK SERTA MENGIKATKAN DIRI DALAM PERJANJIAN INI.</p>

<h3>A. Definisi &amp; Interpretasi</h3>

<p>1. Kecuali konteksnya menentukan lain, ungkapan berikut akan memiliki arti sebagai berikut dalam Ketentuan Penggunaan ini:</p>

<p>&quot;MTICKET&quot;, &quot;kita&rdquo;, atau &quot;kami&quot; merujuk kepada PT EDRUS EXPO ANUGERAH, sebuah perseroan terbatas yang didirikan berdasarkan hukum Indonesia dan beralamat di Green Lake City Ruko Crown Blok D No. 17, Petir, Kec. Cipondoh, Kota Tangerang, Banten 15147</p>

<p>&ldquo;Kamu&rdquo; atau &ldquo;Pengguna&rdquo; merujuk pada setiap orang atau badan hukum yang menggunakan, mengakses, memanfaatkan dan/atau membuat akun di&nbsp;<a href="http://www.mticket.com/" rel="noopener noreferrer" target="_blank">www.mticket.com</a>&nbsp;termasuk namun tidak terbatas pada Event Creator dan Pembeli.</p>

<p>&ldquo;Situs&rdquo; berarti&nbsp;<a href="http://www.mticket.com/" rel="noopener noreferrer" target="_blank">www.mticket.com</a>&nbsp;yang dikelola dan dimiliki oleh MTICKET.</p>

<p>&ldquo;Platform&rdquo; berarti Situs kami, versi mobile dari Situs kami, saluran suara dan data, teknologi, piranti lunak, sistem dan media lain yang dimiliki dan dikelola oleh MTICKET dari waktu ke waktu.</p>

<p>&ldquo;Event&rdquo; berarti suatu kegiatan yang bersifat komersial maupun tidak komersial yang diselenggarakan oleh Event Creator yang menggunakan jasa layanan Platform kami untuk menunjang kegiatan acara tersebut.</p>

<p>&ldquo;Event Creator&rdquo; berarti setiap individu, perkumpulan, badan hukum, dan/atau berbagai badan hukum lainnya yang menyelenggarakan Event sebagai penyelenggara, promotor, panitia dan/atau pemilik yang bekerjasama dengan kami menggunakan layanan Platform kami termasuk namun tidak terbatas pada layanan yang kami sediakan di Situs.</p>

<p>&ldquo;Tiket&rdquo; berarti tanda bukti hak yang sah untuk memasuki tempat berlangsungnya Event, menikmati suatu pertunjukan yang dipertunjukan oleh Event, menggunakan dan/atau memanfaatkan suatu kegiatan yang berhubungan dengan Event yang diselenggarakan Event Creator sesuai dengan tanggal, waktu, tempat, jenis dan/atau ketentuan lainnya yang melekat pada tiket masuk tersebut yang telah dipilih, dipesan dan dibeli secara sah oleh Pembeli, baik berbentuk fisik, elektronik atau bentuk media lainnya yang digunakan oleh kami dari waktu ke waktu dan telah dilengkapi dengan kode unik (barcode) sebagai sistem pengamanan pada tiket tersebut.</p>

<p>&ldquo;Mitra&rdquo; berarti pihak yang telah mengadakan kerja sama dengan kami antara lain termasuk namun tidak terbatas pada kerja sama penggunaan kembali platform kami untuk menyediakan Tiket baik secara daring maupun secara langsung tatap muka atau offline.</p>

<p>&ldquo;Pembeli&rdquo; berarti setiap individua dan/atau badan hukum yang membeli dengan harga tertentu atau secara cuma-cuma Tiket yang diselenggarakan oleh Event Creator secara sah dan sesuai dengan Ketentuan Penggunaan ini, syarat dan ketentuan yang berlaku pada tempat Event, syarat dan ketentuan yang ditetapkan oleh Event Creator, serta peraturan perundang-undangan yang berlaku.</p>

<p>&ldquo;Mticket.asia berarti adalah layanan yang kami sediakan untuk kamu Event Creator berupa penyediaan platform untuk menunjang Event yang memberikan kemudahan dengan penggunaan teknologi untuk Event Creator guna membuat, memasarkan, menjual, dan/atau mendistribusikan Event secara mandiri, dimana layanan tersebut dapat berubah dari waktu ke waktu berdasarkan kebijakan kami sendiri.</p>

<p>&ldquo;Biaya Jasa&rdquo; berarti biaya jasa sebagai imbalan kepada kami atas jasa atau produk layanan kami, termasuk namun tidak terbatas pada penyediaan Platform guna menunjang Event kamu, baik berupa uang, presentase maupun jasa yang dapat dinilai, yang kami tetapkan dari waktu ke waktu berdasarkan kebijakan kami sendiri.</p>

<h3>B. Ketentuan Umum</h3>

<p>Jika terjadi konflik atau inkonsistensi antara dua atau lebih ketentuan dalam Ketentuan Penggunaan ini baik dengan ketentuan penggunaan kami lainnya dan/atau ketentuan penggunaan Mitra kami, apakah ketentuan tersebut tercantum dalam dokumen yang sama atau berbeda, konflik atau inkonsistensi tersebut maka MTICKET akan menentukan ketentuan yang berlaku.</p>

<p>Selain Ketentuan Penggunaan ini dan tergantung pada layanan yang dipilih oleh Kamu, Kamu wajib untuk membaca dan menerima aturan dan ketentuan layanan tersebut yang mungkin akan berlaku untuk layanan tersebut.</p>

<p>Perjanjian ini berlaku selama Kamu, Event Creator menggunakan jasa Kami, baik pada saat penyelenggaraan Event maupun pada saat berakhirnya Event sampai dengan Kamu telah memenuhi seluruh kewajiban Kamu berdasarkan perjanjian ini.</p>

<p>MTICKET akan mempublikasikan setiap perubahan yang bersifat substansial atau amandemen dari Ketentuan Penggunaan ini (apabila ada) melalui Platform. Event Creator diwajibkan untuk membaca dengan baik setiap perubahan atau amandemen tersebut sehingga apabila Event Creator tetap menggunakan, mengakses atau memanfaatkan Platform, Event Creator dianggap telah mengetahui, memahami dan menyetujui perubahan atau amandemen tersebut.</p>

<p>Semua pemesanan Tiket oleh Pembeli untuk Event yang diselenggarakan oleh Event Creator melalui Platform kami, merupakan perikatan terpisah dengan perikatan yang timbul dari perjanjian ini berdasarkan Ketentuan Penggunaan ini, yaitu perikatan yang timbul antara Pembeli dengan Event Creator, yang masing-masing pihak terikat dan tunduk pada perikatan tersebut. Untuk menghindari keragu-raguan, Kami merupakan penyedia Platform yang bekerja sama dengan Event Creator, sedangkan keseluruhan Tiket yang dijual kepada Pembeli adalah milik Event Creator. Segala bentuk data dan informasi mengenai Tiket yang Event Creator sediakan kepada Kami, dan Kami informasikan kepada calon Pembeli, merupakan penawaran dari Event Creator kepada calon Pembeli tersebut dimana mengikat untuk Event Creator dan Pembeli dalam hal terjadi pembelian Tiket tersebut. Oleh sebab itu, Kami bukan termasuk dalam pihak dalam hal terjadi sengketa, penuntutan hak, gugatan hak, permintaan hak, penggantian rugi, kerugian yang timbul, cidera yang timbul, kematian yang timbul dan/atau klaim hak atas hak apapun yang timbul terkait secara langsung maupun tidak langsung dari penyelenggaran Event yang diminta oleh Event Creator kepada Pembeli dan begitupun sebaliknya dari Pembeli kepada Event Creator, termasuk oleh pihak ketiga manapun yang merasa dirugikan oleh penyelenggaraan Event oleh Event Creator.</p>

<p>Untuk menghindari keragu-raguan, Event Creator telah memahami dan menyetujui bahwa MTICKET tidak memberikan jaminan dalam bentuk apapun atas keberhasilan penyelenggaran Event baik dalam bentuk hasil penjualan Tiket maupun kelancaran pelaksanaan Event. Event Creator dengan ini membebaskan dan melepaskan MTICKET dan menanggung dari segala bentuk tuntutan, gugatan, permintaan, kerugian, klaim, dan/atau segala bentuk penggantian hak oleh pihak manapun termasuk Event Creator sendiri yang timbul akibat dari termasuk namun tidak terbatas pada hasil penjualan Tiket dan penyelenggaran Event.</p>

<h3>C. Akun Event Creator</h3>

<p>Setiap Event Creator yang hendak menggunakan dan memanfaatkan layanan kami, termasuk layanan mticket.com, untuk menunjang Event kamu, wajib membuat akun pada sistem MTICKET.</p>

<p>Syarat untuk membuat akun adalah pengisiian data dan informasi oleh Event Creator yang kebenaran, validitas, legalitas, dan keabsahaannya dijamin oleh Kamu.</p>

<p>Setiap perbuatan dan tindakan dengan menggunakan akun tersebut merupakan tanggung jawab penuh Event Creator sebagai pembuat dan pemilik akun tersebut, termasuk segala bentuk penyalahgunaan yang dilakukan oleh pihak lain dan/atau Event Creator sendiri. Oleh sebab itu, Event Creator diwajibkan untuk menjaga kerahasiaan data dan informasi yang berkaitan dengan akun tersebut. Event Creator membebaskan dan melepaskan MTICKET dari tanggung jawab dalam bentuk apapun terkait dengan penggunaan akun tersebut.</p>

<p>Dalam pembuatan akun tersebut, segala data dan informasi yang diisi oleh Event Creator adalah dalam penguasaan dan kepemilikan penuh dari Event Creator, di mana Event Creator bertanggungjawab penuh atas kebenaran setiap data dan informasi yang diisi oleh Event Creator, dan segala bentuk kelalaian, kesalahan, kealpaan, typo, dan/atau kesalahan dalam bentuk dan alasan apapun yang menyebabkan data dan informasi tersebut menjadi tidak bermakna sebagaimana yang akan dimaksud oleh Event Creator menjadi tanggung jawab penuh Event Creator, baik yang menimbulkan kerugian maupun yang tidak, termasuk namun tidak terbatas pada kesalahan nomor rekening, jadwal acara, tempat acara akan menjadi tanggung jawab Event Creator. Event Creator diwajibkan untuk mengisi segala informasi dan data dalam pembuatan akun secara akurat, seksama, hati-hati dan penuh ketelitian.</p>

<p>Kamu sebagai Event Creator dengan ini menyatakan dan menjamin kepada Kami bahwa kamu adalah badan hukum yang berhak, perwakilan sah yang berwenang, pemilik hak, dan/atau telah mendapat seluruh persetujuan yang diperlukan dalam membuat akun serta mengisi segala data dan informasi dalam pembuatan akun Kamu.</p>

<p>Kamu sebagai Event Creator dengan ini menyatakan dan menjamin kepada Kami bahwa segala data dan informasi yang diberikan dan diisi dalam pembuatan akun Kamu merupakan data dan informasi yang legal, valid, sah, dan menjadi kewenangan Kamu untuk kamu berikan kepada Kami.</p>

<p>Kamu dengan ini telah sepakat dan menyetujui bahwa MTICKET memiliki hak dan kewenangan penuh berdasarkan kebijakan Kami sendiri, untuk menghapus, tidak memproses, masukan ke daftar hitam, blokir dan/atau dengan metode dan cara-cara yang Kami anggap perlu untuk menangani setiap akun Event Creator yang Kami anggap telah melanggar Ketentuan Penggunaan ini, melakukan tindak pidana, melanggar ketentuan peraturan perundang-undangan, ketertiban umum, keasusilaan, penipuan, penyalahgunaan, kelalaiaan, kealpaan dan/atau berdasarkan kebijakan Kami yang dapat dipertanggungjawabkan.</p>

<h3>D. Konten Event</h3>

<p>Event Creator yang telah membuat akun pada Situs kami, dapat membuat Event dengan tunduk pada syarat dan ketentuan dalam Ketentuan Penggunaan ini, norma susila, ketertiban umum dan peraturan perundang-undangan yang berlaku.</p>

<p>Event Creator wajib menyediakan kepada Kami secara cuma-cuma tanpa imbalan dalam bentuk apapun semua informasi dan data mengenai Event dengan data dan informasi yang benar. valid, legal, sah, akurat dan tidak melanggar hak kekayaan intelektual pihak lain dalam bentuk apapun. Event Creator dilarang membuat deskripsi mengenai Event yang melanggar ketentuan peraturan perundang-undangan, ketertiban umum, kesusilaan, norma yang berlaku, seperti namun tidak terbatas pada provokasi terhadap suku, agama, ras dan antar golongan (SARA) dan/atau golongan tertentu, pemerasan, pornografi, vulgar, menyudutkan orang atau golongan tertentu, pengancaman, penghinaan, pencemaran nama baik, kekerasan, menakut-nakuti, menyesatkan, bohong, seruan yang menimbulkan rasa kebencian atau permusuhan yang memecah belah, dan/atau seruan untuk melanggar hukum yang berlaku.</p>

<p>Event yang Event Creator selenggarakan dilarang mengandung unsur, baik dalam bentuk penamaan, isi dari Event, kegiatan yang berada dalam Event, tempat dari Event, dan/atau segala bentuk yang termasuk dari unsur-unsur Event tersebut yang berkaitan dan menjadi suatu kesatuan yang saling terkait dalam Event tersebut baik secara langsung maupun tidak langsung, dimana termasuk dari unsur berupa pelanggaran dari ketentuan peraturan perundang-undangan, pencucian uang, ketertiban umum, kesusilaan, norma yang berlaku, seperti namun tidak terbatas pada bentuk perjudian, prostitusi, provokasi terhadap suku, agama, ras dan antar golongan (SARA) dan/atau golongan tertentu, pemerasan, pornografi, pengancaman, penghinaan, pencemaran nama baik, kekerasan, menakut-nakuti, menyesatkan, bohong, seruan yang menimbulkan rasa kebencian atau permusuhan yang memecah belah, yang seluruh kegiatannya hanya berbentuk pengumpulan uang dan/atau barang tanpa adanya kegiatan acara lain, dan/atau seruan untuk melanggar hukum yang berlaku.</p>

<p>Event Creator menyatakan dan menjamin kepada Kami bahwa:</p>

<p>Seluruh informasi dan data yang disediakan kepada Kami, baik berupa poster, gambar, kata-kata, istilah dan/atau segala bentuk ciptaan lainnya yang merupakan hak kekayaan intelektual merupakan hak dan kewenangan dari Event Creator untuk digunakan baik secara ekonomis maupun non komersial bagi kepentingan Event oleh Event Creator;</p>

<p>Event yang diselenggarakan adalah hak, milik, kepunyaan, dan kewenangan penuh dan/atau merupakan kuasa dengan telah diterimanya semua bentuk persetujuan yang diperlukan untuk Event Creator dalam mewakili penyelenggaraan Event;</p>

<p>Penyelenggaraan Event berserta isinya dan tunduknya Event Creator pada perjanjian ini tidak melanggar ketentuan apapun, baik berdasarkan peraturan perundang-undangan, perjanjian lain, perintah pengadilan, perintah badan pemerintahan dan kewajiban-kewajiban apapun dimana Event Creator terikat untuk tunduk pada ketentuan tersebut;</p>

<p>Event Creator bertanggungjawab penuh atas keseluruhan Event termasuk pada isinya, sampingannya ataupun unsur-unsurnya yang terkait dan menjadi satu kesatuan baik secara langsung maupun tidak langsung pada Event tidak melanggar Ketentuan Penggunaan ini, peraturan perundang-undangan, keasusilaan, ketertiban umum, hak kekayaan intelektual pihak lain dan ketentuan-ketentuan lainnya yang harus dipatuhi;</p>

<p>Event Creator telah memperoleh segala bentuk perizinan, persetujuan, rekomendasi, dan/atau segala bentuk dokumen-dokumen lainnya dalam pelaksanaan Event yang diselenggarakan;</p>

<p>Isi dari Event, baik bentuk kegiatan, pengisi kegiatan, jenis kegiatan, tipe kegiatan, acara kegiatan Event termasuk jenis dan tipe Tiket dan segala bentuk yang berkaitan dengan isi Event yang dibuat serta diisi pada sistem MTICKET adalah benar dan sesuai dengan kenyataan yang ada. Dalam hal terjadi perubahan mengenai Event dalam bentuk apapun, termasuk namun tidak terbatas pada tempat, jenis, waktu, kegiatan, sifat komersil menjadi non komersil begitupula sebaliknya, tipe dan klasifikasi Tiket dan perubahan lainnya, Event Creator wajib untuk memberitahu kepada MTICKET dan/atau Pembeli Tiket terhadap perubahan tersebut.</p>

<p>Event Creator dengan ini setuju untuk bertanggungjawab secara penuh dan melepaskan dan membebaskan MTICKET dari segala bentuk tanggung jawab, ganti kerugian, tuntutan, gugatan, klaim hak, permintaan hak dari pihak manapun dan/atau segala bentuk kewajiban yang harus ditanggung akibat dari pelanggaran Ketentuan Penggunaan ini, pelanggaran peraturan perundang-undangan, pelanggaran norma sosial, keasusilaan, ketertiban umum, dan/atau pelanggaran atas hak-hak pihak lain yang merasa haknya dilanggar oleh akibat pelaksanaan Event dan/atau pelanggaran dari larangan, pernyataan dan jaminan, kewajiban dan segala bentuk ketentuan dari Ketentuan Penggunaan ini.</p>

<p>Event Creator bertanggung jawab penuh atas seluruh izin, persetujuan, dispensasi, perintah, lisensi, pajak, pungutan, persetujuan penggunaan hak kekayaan intelektual dan/atau dokumen dalam bentuk apapun yang diperlukan berdasarkan ketentuan peraturan perundang-undangan termasuk kebijakan pemerintahan, yang diperlukan untuk keberlangsungan dan penyelenggaran Event tersebut.</p>

<p>Event Creator dengan ini telah sepakat dan menyetujui bahwa MTICKET memiliki hak dan kewenangan penuh berdasarkan kebijakan Kami sendiri, untuk menolak, menghapus, tidak memproses, masukan ke daftar hitam, blokir, menghentikan kerja sama secara sepihak, menuntut ganti rugi, menuntut berbagai hak untuk memulihkan hak yang telah dilanggar dan/atau dengan metode dan cara-cara yang Kami anggap perlu untuk menangani setiap Event yang Kami anggap telah melanggar Ketentuan Penggunaan ini, melakukan tindak pidana, melanggar ketentuan peraturan perundang-undangan, ketertiban umum, keasusilaan, penipuan, penyalahgunaan, kelalaiaan, kealpaan dan/atau berdasarkan kebijakan Kami yang dapat dipertanggungjawabkan.</p>

<h3>E. Ketentuan Pembayaran</h3>

<p>Setiap Event yang diselenggarakan oleh Event Creator dalam Platform kami, maka Kami berhak atas Biaya Jasa sebesar sebagaimana tercantum di&nbsp;<a href="https://www.mticket.com/panduan" rel="noopener noreferrer" target="_blank">https://www.MTICKET.com/panduan</a>&nbsp;.</p>

<p>Sebelum melakukan penagihan atas uang hasil penjualan Tiket Event yang terjual melalui sistem MTICKET, Event Creator wajib untuk mengisi dan menyediakan data dan informasi yang diperlukan oleh Kami sekurang-kurangnya sebagaimana tercantum di&nbsp;<a href="https://www.mticket.com/panduan" rel="noopener noreferrer" target="_blank">https://www.MTICKET.com/panduan</a>&nbsp;.</p>

<p>Event Creator dapat melakukan penagihan atas uang hasil penjualan Tiket Event yang terjual melalui sistem MTICKET setelah Event berakhir dan telah memenuhi semua syarat dan ketentuan yang berlaku.</p>

<p>MTICKET baru akan melakukan proses pembayaran atas tagihan sebagaimana dimaksud pada ayat (2) dan (3) di atas maksimal 10 (sepuluh) hari kerja sejak diterimanya dan telah lengkapnya seluruh persyaratan yang diperlukan yang disediakan oleh Event Creator.</p>

<p>Pembayaran atas hasil penjualan Tiket akan dilakukan oleh MTICKET dengan cara transfer dana ke rekening Event Creator berdasarkan data dan informasi yang telah diisi oleh Event Creator. Segala bentuk kesalahan dari pengisian data dan informasi rekening Event Creator yang menyebabkan keterlambatan, kegagalan, kerugian, pengurangan dan segala bentuk akibat yang timbul akibat dari hal tersebut, bukan merupakan tanggung jawab dari MTICKET sehingga Event Creator setuju dan memahami untuk melepaskan dan membebaskan MTICKET atas tanggung jawab terhadap hal tersebut. Oleh karena itu, Event Creator wajib secara seksama, akurat, teliti, cermat, hati-hati dan benar terhadap rekening milik Event Creator.</p>

<p>Event Creator menjamin dan bertanggung jawab penuh bahwa data dan informasi rekening merupakan rekening yang sah, valid, legal dan milik dari Event Creator yang mewakili Event tersebut. Untuk menghindari keragu-raguan, Event Creator melepaskan dan membebaskan MTICKET dan akan menanggung segala bentuk tuntutan, gugatan, permintaan, perintah dan klaim oleh pihak manapun termasuk oleh Event Creator sendiri atas hasil penjualan Tiket yang MTICKET kirim pada rekening berdasarkan data dan informasi yang Event Creator isi tersebut.</p>

<p>Event Creator bertanggung jawab penuh atas seluruh pajak, pungutan, kontribusi, retribusi, biaya, bunga dan/atau tagihan dalam bentuk apapun yang menjadi kewajiban yang harus dilakukan dalam pelaksanaan dan penyelenggaraan Event.</p>

<p>Pembayaran atas penjualan Tiket Event yang diberikan kepada Event Creator berdasarkan laporan penjualan yang tercantum dalam sistem MTICKET, akan dibayarkan setelah dipotong dengan Biaya Jasa kami, termasuk pajak pertambahan nilai (PPN).</p>

<p>Kecuali ditentukan lain dalam perjanjian ini, semua jenis pajak, biaya ataupun pungutan lainnya, baik yang ada saat ini maupun yang ada dikemudian hari, yang wajib dibayarkan ke pemerintah yang berkaitan dengan transaksi berdasarkan perjanjian ini, wajib ditanggung oleh Event Creatorajak sesuai ketentuan perundang-undangan yang berlaku.</p>

<p>Dalam hal Event Creator tidak melakukan penagihan haknya, termasuk hasil penjualan Tiket, yang berada pada Kami selambat-lambatnya 30 hari kalender sejak berakhirnya Event, maka dengan ini Event Creator telah menyetujui untuk memberikan hak tersebut kepada Kami, dan hak tersebut menjadi hak dan milik MTICKET sepenuhnya.</p>

<p>F. Perubahan dan Pembatalan Acara</p>

<p>Dalam hal terjadi perubahan kegiatan Event yang diakibatkan oleh satu dan lain hal, maka Event Creator wajib memberitahukan kepada Kami dan Pembeli secara resmi paling lambat 7 (tujuh) hari sebelum perubahan kegiatan Event tersebut.</p>

<p>Dalam hal terjadi pembatalan Event, MTICKET tetap berhak atas Biaya Jasa yang telah dilakukannya dan biaya-biaya lainnya yang telah dikeluarkan Pihak Kedua yang berkaitan dengan pelaksanaan kerja sama, termasuk biaya administrasi bank untuk transfer pengembalian uang kepada Pembeli ( refund) dan biaya-biaya lainnya, yang akan ditagihkan kepada Event Creator.</p>

<p>Dalam hal terjadi pembatalan Event, Event Creator bertanggung jawab secara penuh untuk mengembalikan uang hasil pembelian Tiket oleh Pembeli kepada Pembeli melalui MTICKET dengan melakukan pembayaran biaya-biaya sebagaimana di maksud Huruf (F) poin (2) di atas dengan ditambah dengan total uang pengembalian Tiket, dimana total tersebut akan dikurangkan dengan uang hasil pembelian Tiket dan kekurangan uang tersebut wajib dibayar oleh Event Creator paling lambat 7 (tujuh) hari melalui rekening Kami yang akan kami berikan berserta jumlah yang harus dibayar kepada Event Creator.</p>

<p>Jumlah uang pengembalian atas pembatalan Event kepada Pembeli adalah sebesar 100% (seratus persen) dari harga Tiket dan tidak termasukconvinience fee yang sudah dipotong oleh pihak bank dan payment gateway (jika transaksi dilakukan dengan fasilitas pembayaran dari perusahaan payment gateway) atau biaya-biaya lainnya yang akan ditanggung oleh Event Creator, sesuai sebagaimana dimaksud dalam Huruf (F) poin (2) dan (3) di atas.</p>

<h3>G. Perizinan</h3>

<p>Dengan tergantung pada kepatuhan Pengguna pada Ketentuan Penggunaan, kami memberikan Pengguna ijin yang terbatas, non-eksklusif, tidak dapat dipindahtangankan, tidak dapat dialihkan, tidak dapat disublisensikan, ijin yang dapat ditarik untuk mengunduh dan memasang salinan Situs pada suatu perangkat bergerak tunggal yang Pengguna miliki atau kontrol dan menjalankan salinan Situs semata-mata untuk kebutuhan pribadi, non-komersial Pengguna sendiri.</p>

<p>Pengguna tidak diperkenankan (i) menyalin, memodifikasi, mengadaptasi, menerjemahkan, membuat karya turunan dari, mendistribusikan, memberikan lisensi, menjual, mengalihkan, menampilkan di muka umum, membuat ulang, mentransmisikan, memindahkan, menyiarkan, menguraikan, atau membongkar bagian manapun dari atau dengan cara lain yang mungkin mengeksploitasi Situs, kecuali sebagaimana diperbolehkan dalam Ketentuan Penggunaan ini, (ii) memberikan lisensi, mensublisensikan, menjual, menjual kembali, memindahkan, mengalihkan, mendistribusikan atau mengeksploitasi secara komersial atau membuat tersedia kepada pihak ketiga Situs dan / atau perangkat lunak dengan cara; (iii) menciptakan &quot;link&quot;internet ke Situs atau &quot;frame&quot; atau &quot;mirror&quot; setiap perangkat lunak pada server lain atau perangkat nirkabel atau yang berbasis internet; (iv) merekayasa ulang atau mengakses perangkat lunak kami untuk (a) membangun produk atau layanan tandingan, (b) membangun produk dengan menggunakan ide, fitur, fungsi atau grafis sejenis Situs, atau (c) menyalin ide, fitur, fungsi atau grafis Situs, (v) meluncurkan program otomatis atau script, termasuk, namun tidak terbatas pada, web spiders, web crawlers, web robots, web ants, web indexers, bots, virus atau worm, atau segala program apapun yang mungkin membuat beberapa permintaan server per detik, atau menciptakan beban berat atau menghambat operasi dan/atau kinerja Situs, (vi) menggunakan robot, spider, pencarian situs/Situs pengambilan kembali, atau perangkat manual atau otomatis lainnya atau proses untuk mengambil, indeks, &quot;tambang data&quot; (data mine), atau dengan cara apapun memperbanyak atau menghindari struktur navigasi atau presentasi dari Situs atau isinya; (vii) menerbitkan, mendistribusikan atau memperbanyak dengan cara apapun materi yang dilindungi hak cipta, merek dagang, atau informasi yang dimiliki lainnya tanpa memperoleh persetujuan terlebih dahulu dari pemilik hak milik, (viii) menghapus setiap hak cipta, merek dagang atau pemberitahuan hak milik lainnya yang terkandung dalam Situs. Tidak ada lisensi atau hak yang diberikan kepada Pengguna dengan implikasi berdasarkan hak kekayaan intelektual dimiliki atau dikendalikan oleh kami atau pemberi lisensi kami, kecuali untuk lisensi dan hak tersebut secara tegas diberikan dalam Ketentuan Penggunaan ini.</p>

<p>Pengguna tidak diperkenankan (i) menyalin, memodifikasi, mengadaptasi, menerjemahkan,membuat karya turunan dari, mendistribusikan, memberikan lisensi, menjual, mengalihkan, menampilkan di muka umum, membuat ulang, mentransmisikan, memindahkan, menyiarkan, menguraikan, atau membongkar bagian manapun dari atau dengan cara lain yang mungkin mengeksploitasi Situs, kecuali sebagaimana diperbolehkan dalam Ketentuan Penggunaan ini, (ii) memberikan lisensi, mensublisensikan, menjual, menjual kembali, memindahkan, mengalihkan, mendistribusikan atau mengeksploitasi secara komersial atau membuat tersedia kepada pihak ketiga Situs dan / atau perangkat lunak dengan cara; (iii) menciptakan &quot;link&quot; internet ke Situs atau &quot;frame&quot; atau &quot;mirror&quot; setiap perangkat lunak pada server lain atau perangkat nirkabel atau yang berbasis internet; (iv) merekayasa ulang atau mengakses perangkat lunak kami untuk (a) membangun produk atau layanan tandingan, (b) membangun produk dengan menggunakan ide, fitur, fungsi atau grafis sejenis Situs, atau (c) menyalin ide, fitur, fungsi atau grafis Situs, (v) meluncurkan program otomatis atau script, termasuk, namun tidak terbatas pada, web spiders, web crawlers, web robots, web ants, web indexers, bots, virus atau worm, atau segala program apapun yang mungkin membuat beberapa permintaan server per detik, atau menciptakan beban berat atau menghambat operasi dan/atau kinerja Situs, (vi) menggunakan robot, spider, pencarian situs/Situs pengambilan kembali, atau perangkat manual atau otomatis lainnya atau proses untuk mengambil, indeks, &quot;tambang data&quot; (data mine), atau dengan cara apapun memperbanyak atau menghindari struktur navigasi atau presentasi dari Situs atau isinya; (vii) menerbitkan, mendistribusikan atau memperbanyak dengan cara apapun materi yang dilindungi hak cipta, merek dagang, atau informasi yang dimiliki lainnya tanpa memperoleh persetujuan terlebih dahulu dari pemilik hak milik, (viii) menghapus setiap hak cipta, merek dagang atau pemberitahuan hak milik lainnya yang terkandung dalam Situs. Tidak ada lisensi atau hak yang diberikan kepada Pengguna dengan implikasi berdasarkan hak kekayaan intelektual dimiliki atau dikendalikan oleh kami atau pemberi lisensi kami, kecuali untuk lisensi dan hak tersebut secara tegas diberikan dalam Ketentuan Penggunaan ini.</p>

<p>Pengguna tidak diperkenankan (i) menyalin, memodifikasi, mengadaptasi, menerjemahkan, membuat karya turunan dari, mendistribusikan, memberikan lisensi, menjual, mengalihkan, menampilkan di muka umum, membuat ulang, mentransmisikan, memindahkan, menyiarkan, menguraikan, atau membongkar bagian manapun dari atau dengan cara lain yang mungkin mengeksploitasi Situs, kecuali sebagaimana diperbolehkan dalam Ketentuan Penggunaan ini, (ii) memberikan lisensi, mensublisensikan, menjual, menjual kembali, memindahkan, mengalihkan, mendistribusikan atau mengeksploitasi secara komersial atau membuat tersedia kepada pihak ketiga Situs dan / atau perangkat lunak dengan cara; (iii) menciptakan &quot;link&quot; internet ke Situs atau &quot;frame&quot; atau &quot;mirror&quot; setiap perangkat lunak pada server lain atau perangkat nirkabel atau yang berbasis internet; (iv) merekayasa ulang atau mengakses perangkat lunak kami untuk (a) membangun produk atau layanan tandingan, (b) membangun produk dengan menggunakan ide, fitur, fungsi atau grafis sejenis Situs, atau (c) menyalin ide, fitur, fungsi atau grafis Situs, (v) meluncurkan program otomatis atau script, termasuk, namun tidak terbatas pada, web spiders, web crawlers, web robots, web ants, web indexers, bots, virus atau worm, atau segala program apapun yang mungkin membuat beberapa permintaan server per detik, atau menciptakan beban berat atau menghambat operasi dan/atau kinerja Situs, (vi) menggunakan robot, spider, pencarian situs/Situs pengambilan kembali, atau perangkat manual atau otomatis lainnya atau proses untuk mengambil, indeks, &quot;tambang data&quot; (data mine), atau dengan cara apapun memperbanyak atau menghindari struktur navigasi atau presentasi dari Situs atau isinya; (vii) menerbitkan, mendistribusikan atau memperbanyak dengan cara apapun materi yang dilindungi hak cipta, merek dagang, atau informasi yang dimiliki lainnya tanpa memperoleh persetujuan terlebih dahulu dari pemilik hak milik, (viii) menghapus setiap hak cipta, merek dagang atau pemberitahuan hak milik lainnya yang terkandung dalam Situs. Tidak ada lisensi atau hak yang diberikan kepada Pengguna dengan implikasi berdasarkan hak kekayaan intelektual dimiliki atau dikendalikan oleh kami atau pemberi lisensi kami, kecuali untuk lisensi dan hak tersebut secara tegas diberikan dalam Ketentuan Penggunaan ini.</p>

<p>Pengguna tidak diperkenankan (i) menyalin, memodifikasi, mengadaptasi, menerjemahkan, membuat karya turunan dari, mendistribusikan, memberikan lisensi, menjual, mengalihkan, menampilkan di muka umum, membuat ulang, mentransmisikan, memindahkan, menyiarkan, menguraikan, atau membongkar bagian manapun dari atau dengan cara lain yang mungkin mengeksploitasi Situs, kecuali sebagaimana diperbolehkan dalam Ketentuan Penggunaan ini, (ii) memberikan lisensi, mensublisensikan, menjual, menjual kembali, memindahkan, mengalihkan, mendistribusikan atau mengeksploitasi secara komersial atau membuat tersedia kepada pihak ketiga Situs dan / atau perangkat lunak dengan cara; (iii) menciptakan &quot;link&quot; internet ke Situs atau &quot;frame&quot; atau &quot;mirror&quot; setiap perangkat lunak pada server lain atau perangkat nirkabel atau yang berbasis internet; (iv) merekayasa ulang atau mengakses perangkat lunak kami untuk (a) membangun produk atau layanan tandingan, (b) membangun produk dengan menggunakan ide, fitur, fungsi atau grafis sejenis Situs, atau (c) menyalin ide, fitur, fungsi atau grafis Situs, (v) meluncurkan program otomatis atau script, termasuk, namun tidak terbatas pada, web spiders, web crawlers, web robots, web ants, web indexers, bots, virus atau worm, atau segala program apapun yang mungkin membuat beberapa permintaan server per detik, atau menciptakan beban berat atau menghambat operasi dan/atau kinerja Situs, (vi) menggunakan robot, spider, pencarian situs/Situs pengambilan kembali, atau perangkat manual atau otomatis lainnya atau proses untuk mengambil, indeks, &quot;tambang data&quot; (data mine), atau dengan cara apapun memperbanyak atau menghindari struktur navigasi atau presentasi dari Situs atau isinya; (vii) menerbitkan, mendistribusikan atau memperbanyak dengan cara apapun materi yang dilindungi hak cipta, merek dagang, atau informasi yang dimiliki lainnya tanpa memperoleh persetujuan terlebih dahulu dari pemilik hak milik, (viii) menghapus setiap hak cipta, merek dagang atau pemberitahuan hak milik lainnya yang terkandung dalam Situs.Tidak ada lisensi atau hak yang diberikan kepada Pengguna dengan implikasi berdasarkan hak kekayaan intelektual dimiliki atau dikendalikan oleh kami atau pemberi lisensi kami, kecuali untuk lisensi dan hak tersebut secara tegas diberikan dalam Ketentuan Penggunaan ini.</p>

<h3>H. Hak Kekayaan Intelektual</h3>

<p>Kami menyediakan Kamu dengan konten seperti suara, foto, gambar, video atau materi lain yang terkandung dalam iklan disponsori atau informasi. Bahan ini dapat dilindungi oleh hak cipta, merek dagang atau hak kekayaan intelektual lainnya dan undang- undang. Kamu dapat menggunakan bahan ini hanya secara tegas diizinkan oleh MTICKET dan tidak akan menyalin, mengirimkan atau membuat karya turunan dari materi tersebut tanpa izin tertulis dari MTICKET.</p>

<p>Kamu mengakui dan setuju bahwa Kamu tidak akan mengunduh, posting, memperbanyak atau mendistribusikan konten apapun atau melalui Platform yang dilindungi oleh hak cipta atau hak milik lainnya dari pihak ketiga, tanpa memperoleh izin dari pemilik hak tersebut. Setiap konten eksklusif hak cipta atau lainnya didistribusikan atau melalui Platform dengan persetujuan dari pemilik harus berisi hak cipta yang sesuai atau pemberitahuan hak kepemilikan lainnya. Pengajuan atau distribusi konten eksklusif hak cipta atau lainnya yang tidak sah adalah ilegal dan bisa dikenai tanggung jawab pribadi atau penuntutan pidana.</p>

<h3>I. Jaminan</h3>

<p>Kami tidak memberikan pernyataan, jaminan atau garansi untuk dapat diandalkannya, ketepatan waktu, kualitas, kesesuaian, ketersediaan, akurasi atau kelengkapan dari layanan, Situs kami dan/atau Platform kami, termasuk namun tidak terbatas pada Layanan yang diperoleh atau berasal dari Mitra kami melalui penggunaan Platform tersebut. Kami tidak menyatakan atau menjamin bahwa (a) penggunaan Platform akan aman, tepat waktu, tanpa gangguan atau terbebas dari kesalahan atau beroperasi dengan kombinasi dengan perangkat keras lain, perangkat lunak, sistem atau data, (b) layanan akan memenuhi kebutuhan atau harapan Kamu, (c) setiap data yang tersimpan akan akurat atau dapat diandalkan, (d) kualitas produk, layanan, informasi, atau bahan-bahan lain yang dibeli atau diperoleh oleh Kamu melalui Platform akan memenuhi kebutuhan atau harapan Kamu, (e) kesalahan atau kecacatan dalam Platform akan diperbaiki, atau (f) Platform atau server(-server) yang menyediakan Platform terbebas dari virus atau komponen berbahaya lainnya. Layanan disediakan untuk Kamu terbatas hanya pada dasar &quot;sebagaimana adanya&quot;. Semua kondisi, pernyataan dan jaminan, baik tersurat, tersirat, yang diwajibkan oleh undang-undang atau sebaliknya, termasuk, namun tidak terbatas pada, jaminan yang tersirat mengenai jual beli, kesesuaian untuk tujuan tertentu, atau tidak adanya pelanggaran hak pihak ketiga, dengan ini dikecualikan dan dikesampingkan dengan batas tertinggi dan maksimum. Kamu mengakui dan menyetujui bahwa seluruh risiko yang timbul dari penggunaan Platform oleh Kamu tetap semata-mata dan sepenuhnya ada pada Kamu dan Kamu tidak akan memiliki hak untuk meminta ganti rugi apapun dari Kami.</p>

<h3>J. Larangan</h3>

<p>Sebagai kondisi penggunaan platform, Kamu menjamin bahwa Kamu tidak akan menggunakan Platform ini untuk tujuan apapun yang melanggar hukum atau ilegal di bawah hukum untuk saat ini berlaku dalam atau di luar Indonesia atau dilarang oleh syarat dan ketentuan dan / atau Ketentuan Penggunaan ini termasuk secara spesifik dan/atau tersirat. Selain itu, Platform tidak boleh digunakan dengan cara apapun, yang dapat merusak, melumpuhkan, membebani atau mengganggu penggunaan pihak lain dan/atau pengguna Platform. Kamu harus patuh dan taat untuk memperoleh atau mencoba untuk memperoleh bahan atau informasi melalui cara yang dibuat dan tersedia atau disediakan melalui Platform ini dengan iktikad baik.</p>

<h3>K. Pelanggaran</h3>

<p>Tanpa mengurangi aturan lain yang tersedia pada Ketentuan Penggunaan ini, peraturan Kami atau berdasarkan hukum yang berlaku, Kami dapat membatasi aktivitas anda, memperingatkan Pembeli ataupun pihak lain dari tindakan anda, menurunkan dan/atau membatalkan Event Kamu, sifatnya sementara/selamanya menangguhkan atau menghentikan pendaftaran dan/atau Event Kamu, termasuk namun tidak terbatas pada akun dan/atau Event anda, dan/atau menolak untuk memberikan akses ke Platform, dan/atau tindakan-tindakan lainnya berdasarkan kebijakan Kami, jika:</p>

<p>Kamu melanggar Ketentuan Penggunaan ini, peraturan perundang-undangan dan/atau dokumen lain yang terkait;</p>

<p>data dan/atau informasi yang diberikan oleh Kamu tidak sah, valid, legal, palsu dan/atau tidak dapat terverifikasi oleh Kami; atau</p>

<p>Kami percaya bahwa tindakan Kamu mungkin dapat melanggar hak pihak ketiga atau melanggar hukum yang berlaku atau mengakibatkan kewajiban bagi kita, Kamu dan / atau pengguna lainnya termasuk calon Pembeli.</p>

<p>Dengan tunduk dengan peraturan lainnya dalam Ketentuan Penggunaan ini, dalam hal Event Kamu dibatalkan oleh MTICKET karena melanggar salah satu dari Ketentuan Penggunaan ini dan/atau peraturan perundang-undangan yang berlaku, maka uang yang terkumpul akan MTICKET berikan kepada Pembeli.</p>

<h3>L. Batasan Tanggung Jawab</h3>

<p>Kami tidak bertanggung jawab atas setiap cidera, kematian, kerusakan atau kerugian yang terjadi di Event dan/atau penggunaan Platform. Kami juga tidak bertanggung jawab atas kesalahan, termasuk pelanggaran, atau tindakan kriminal yang dilakukan oleh Pembeli atapun pihak lain yang berada dalam tempat Event berlangsung selama pelaksanaan Event, termasuk Event Creator sendiri.</p>

<p>Kami tidak bertanggung jawab dan Kamu menjamin dan membebaskan Kami, Mitra kami, dan perusahaan afiliasi Kami dari tanggung jawab atas setiap kerugian,tuntutan, gugatan dan/atau permintaan hak-hak apapun oleh Kamu, Pembeli, pengunjung acara dan/atau pihak ketiga atas penyalahgunaan, fraud, perbuatan curang dan/atau tindakan-tindakan lainnya akibat dari penyebaran informasi dan/atau data Event, termasuk data/informasi Tiket Event, yang Kamu lakukan sendiri dan/atau akibat dari kelalaian, kealpaan dan/atau kesengajaan Kamu. Oleh karena itu, Kamu diwajibkan untuk menjaga dan tidak menyebarkan informasi dan data pribadi Kamu sendiri, termasuk akun Kamu.</p>

<p>Setiap tuntutan terhadap Kami dalam hal apapun oleh Kamu, akan dibatasi dengan jumlah total yang sebenarnya dibayar oleh dan/atau terutang pada Kamu ketika menggunakan layanan Kami selama peristiwa yang menimbulkan klaim tersebut. Dalam hal apapun Kami dan/atau pemberi lisensi Kami tidak akan bertanggung jawab kepada Kamu atau siapa pun atas biaya, bunga, kerusakan atau kerugian dalam segala jenis atau bentuk (termasuk cedera pribadi, gangguan emosi dan hilangnya data, barang, pendapatan, keuntungan, penggunaan atau keuntungan ekonomi lainnya). Kami tidak akan bertanggung jawab atas kerugian, kerusakan atau cedera yang mungkin ditimbulkan oleh atau disebabkan oleh Kamu pada saar Event berlangsung ataupun dalam rangka pelaksanaan perjanjian ini atau pada setiap orang untuk siapa Kamu telah memesan layanan, termasuk namun tidak terbatas pada kerugian, kerusakan atau cedera yang timbul dari, atau dengan cara apapun sehubungan dengan layanan dan/atau Platform, termasuk namun tidak terbatas pada penggunaan atau ketidakmampuan untuk menggunakan layanan dan/atau Platform dan/atau Situs Kami.</p>

<p>Kamu secara tegas mengesampingkan dan melepaskan kami dari setiap dan semua kewajiban, tuntutan atau kerusakan yang timbul dari atau dengan cara apapun sehubungan dengan Pembeli, mitra Kamu, Mitra, pengunjung Event, pihak yang berada pada Event dan/atau Event. Kami dan perusahaan afiliasi Kami tidak akan menjadi pihak dalam sengketa, negosiasi sengketa antara Kamu dengan pihak manapun. Tanggung jawab untuk keputusan yang Kamu buat atas Event merupakan tanggung jawab dan melekat seutuhnya dengan dan pada Kamu. Kamu secara tegas mengesampingkan dan melepaskan kami dari setiap dan semua kewajiban, tuntutan, penyebab tindakan, atau kerusakan yang timbul dari penggunaan Platform, pelaksanaan Event, perangkat lunak dan/atau Platform, atau dengan cara apapun terkait dengan Kami dan Mitra Kami yang diperkenalkan kepada Kamu melalui Platform.</p>

<p>Kami akan mengambil langkah yang sifatnya wajar untuk mencegah penipuan internet dan memastikan data yang dikumpulkan oleh Kami dan disimpan supaya aman. Namun, kami tidak bertanggung jawab dalam hal dari pelanggaran di server komputer Kamu, Kami tidak bertanggung jawab sebagai pihak ketiga.</p>

<h3>M. Ganti Rugi</h3>

<p>Dengan menggunakan layanan Kami ini, Kamu setuju bahwa Kamu akan membela, memberikan ganti rugi dan membebaskan Kami, pemberi lisensi, afiliasi, dan masing-masing dari petugas, direktur, komisaris, karyawan, pengacara dan agen kami dari dan terhadap setiap dan semua klaim, biaya, kerusakan, kerugian, kewajiban dan biaya (termasuk biaya dan ongkos pengacara) yang timbul dari atau sehubungan dengan: (a) penggunaan layanan pada Situs Kami dan/atau Platform oleh Kamu, hubungan Kamu dengan Pembeli, penyedia pihak ketiga, mitra, pemasang iklan dan/atau sponsor, atau (b) pelanggaran atas atau tidak dipatuhinya salah satu Ketentuan Penggunaan atau peraturan perundang-undangan yang berlaku, baik yang disebutkan di sini atau tidak atau (c) pelanggaran Kamu terhadap hak-hak pihak ketiga, termasuk mitra pihak ketiga dan Mitra Kami, atau (d) penggunaan atau penyalahgunaan layanan Platform Kami. Kewajiban pembelaan dan pemberian ganti rugi ini akan tetap berlaku walaupun Ketentuan Penggunaan dan penggunaan Situs oleh Kamu dan Event telah berakhir.</p>

<h3>N. Ketentuan Lain</h3>

<p>Jika ada ketentuan dalam Ketentuan Penggunaan ini yang ditentukan secara tidak sah atau tidak dapat diterapkan secara keseluruhan atau sebagian, cacat atau harus diterjemahkan hanya untuk ketentuan tersebut atau bagian dari ketentuan tersebut dan sisa bagian dari ketentuan tersebut dan semua ketentuan lain dari syarat ini kondisi akan terus berada dan berlaku sepenuhnya, sedangkan ketentuan tersebut akan Kami sesuaikan sehingga dapat dilaksanakan dan sepenuhnya disetujui oleh Kamu.</p>

<p>Syarat dan ketentuan akan diatur oleh dan ditafsirkan sesuai dengan hukum Republik Indonesia. Penyelesaian sengketa yang terjadi di antara Kamu dan Kami akan diselesaikan secara musyarawah selama 30 (hari) dan jika terjadi kesepakatan akan diselesaikan melalui dan tunduk pada peraturan yang berlaku pada Badan Abritrase Nasional Indonesia.</p>

<p>Dari waktu ke waktu, Kami dapat secara sepihak merubah, merevisi, memperbaiki, menghapus, menambahkan dan/atau merubah dengan bentuk apapun dari syarat dan ketentuan yang tertuang dalam Ketentuan Penggunaan ini berdasarkan kebijakan dan kewenangan Kami.</p>

            </div>  
        </div>  
    </div>  
</section>
@endsection